### ISSUE TITLE
llvmlite install 

### ISSUE THREAD

**Issue by liamconnor** [thepetabyteproject/burstfit#5]
Installing burstfit in some virtual envs will produce the following error, produced by YOUR's dependency on llvmlite:

ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Solution:
pip install llvmlite --ignore-installed

**Comment by KshitijAggarwal** [comment]
Thanks! 

here are some relevant links:  
https://pyautolens.readthedocs.io/en/latest/installation/troubleshooting.html 

https://github.com/NVIDIA/NeMo/issues/841
